# SDTEF - Homelessness Program Analysis

## Setup

In [14]:
import pandas as pd
import numpy as np

## Data Cleaning `updated_dataset.csv`

In [15]:
# Load dataframe
exp = pd.read_csv('../data/processed/updated_dataset.csv')
exp

,Unique.ID,Grantor,Grantee,Program,Year,Date,EndDate,Amount,AmendmentNumber,Funding.Agency,...,Issued,Funding.Type,Years,Average.By.Year,City.Year,Population,Amount.Per.Capita,Amount.Per.PEH,Population.PEH,ExpenditureType
0,NaN,City of Imperial Beach,NaN,NaN,2022.0,NaN,NaN,0,NaN,NaN,...,NaN,NaN,NaN,NaN,City of Imperial Beach|2022,NaN,$0.00,$0.00,0.0,Other/Unknown
1,NaN,City of Imperial Beach,NaN,NaN,2021.0,NaN,NaN,0,NaN,NaN,...,NaN,NaN,NaN,NaN,City of Imperial Beach|2021,NaN,$0.00,$0.00,0.0,Other/Unknown
2,NaN,City of Imperial Beach,NaN,NaN,2020.0,NaN,NaN,0,NaN,NaN,...,NaN,NaN,NaN,NaN,City of Imperial Beach|2020,NaN,$0.00,$0.00,16.0,Other/Unknown
3,NaN,City of Imperial Beach,NaN,NaN,2019.0,NaN,NaN,0,NaN,NaN,...,NaN,NaN,NaN,NaN,City of Imperial Beach|2019,NaN,$0.00,$0.00,12.0,Other/Unknown
4,NaN,City of Imperial Beach,NaN,NaN,2018.0,NaN,NaN,0,NaN,NaN,...,NaN,NaN,NaN,NaN,City of Imperial Beach|2018,NaN,$0.00,$0.00,7.0,Other/Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026,1066,City of Chula Vista,ONE TIME VENDOR,motel voucher,2021.0,12/23/2021,NaN,$560.30,NaN,CDBG,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Crisis Management
2027,NaN,City of Chula Vista,KIKU GARDENS,rental assistance,2021.0,12/28/2021,NaN,$212.00,NaN,HOME,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Prevention
2028,NaN,City of Chula Vista,KIKU GARDENS,rental assistance,2021.0,12/28/2021,NaN,$212.00,NaN,HOME,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Prevention
2029,NaN,City of Chula Vista,KIKU GARDENS,rental assistance,2021.0,12/28/2021,NaN,$212.00,NaN,HOME,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Prevention
2030,NaN,City of Chula Vista,"MARK II, LP",rental assistance,2021.0,12/28/2021,NaN,"$1,668.00",NaN,Housing Authority,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Prevention

In [16]:
# Remove NAs in the Date column
exp = exp[exp['Date'].notna()]
exp

,Unique.ID,Grantor,Grantee,Program,Year,Date,EndDate,Amount,AmendmentNumber,Funding.Agency,...,Issued,Funding.Type,Years,Average.By.Year,City.Year,Population,Amount.Per.Capita,Amount.Per.PEH,Population.PEH,ExpenditureType
8,NaN,City of Chula Vista,SBCS CORPORATION,rental assistance,2017.0,10/23/2017,NaN,"$14,142.74",NaN,NaN,...,NaN,NaN,NaN,NaN,City of Chula Vista|2017,266427.0,$0.05,$38.54,367.0,Prevention
9,NaN,City of Chula Vista,SBCS CORPORATION,rental assistance,2017.0,10/23/2017,NaN,"$12,931.10",NaN,NaN,...,NaN,NaN,NaN,NaN,City of Chula Vista|2017,266427.0,$0.05,$35.23,367.0,Prevention
10,NaN,City of Chula Vista,SBCS CORPORATION,rental assistance,2017.0,10/23/2017,NaN,"$10,285.61",NaN,NaN,...,NaN,NaN,NaN,NaN,City of Chula Vista|2017,266427.0,$0.04,$28.03,367.0,Prevention
11,1068,City of Chula Vista,SBCS CORPORATION,homeless services,2017.0,11/7/2017,NaN,$276.00,NaN,NaN,...,NaN,NaN,NaN,NaN,City of Chula Vista|2017,266427.0,$0.00,$0.75,367.0,Crisis Management
12,1067,City of Chula Vista,INTERFAITH SHELTER NETWORK,shelter,2017.0,11/8/2017,NaN,"$1,971.50",NaN,NaN,...,NaN,NaN,NaN,NaN,City of Chula Vista|2017,266427.0,$0.01,$5.37,367.0,Crisis Management
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026,1066,City of Chula Vista,ONE TIME VENDOR,motel voucher,2021.0,12/23/2021,NaN,$560.30,NaN,CDBG,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Crisis Management
2027,NaN,City of Chula Vista,KIKU GARDENS,rental assistance,2021.0,12/28/2021,NaN,$212.00,NaN,HOME,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Prevention
2028,NaN,City of Chula Vista,KIKU GARDENS,rental assistance,2021.0,12/28/2021,NaN,$212.00,NaN,HOME,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Prevention
2029,NaN,City of Chula Vista,KIKU GARDENS,rental assistance,2021.0,12/28/2021,NaN,$212.00,NaN,HOME,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Prevention
2030,NaN,City of Chula Vista,"MARK II, LP",rental assistance,2021.0,12/28/2021,NaN,"$1,668.00",NaN,Housing Authority,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Prevention

In [17]:
exp.columns

Index(['Unique.ID', 'Grantor', 'Grantee', 'Program', 'Year', 'Date', 'EndDate',
       'Amount', 'AmendmentNumber', 'Funding.Agency', 'Funding.Source',
       'Category', 'Location', 'Issued', 'Funding.Type', 'Years',
       'Average.By.Year', 'City.Year', 'Population', 'Amount.Per.Capita',
       'Amount.Per.PEH', 'Population.PEH', 'ExpenditureType'],
      dtype='object')

In [18]:
columns_to_drop = ['Unique.ID', 'EndDate', 'AmendmentNumber', 'Funding.Agency', 'Funding.Source',
       'Category', 'Location', 'Issued', 'Funding.Type', 'Years',
       'Average.By.Year', 'City.Year', 'Population', 'Amount.Per.Capita',
       'Amount.Per.PEH', 'Population.PEH']
exp = exp.drop(columns=columns_to_drop)
exp

,Grantor,Grantee,Program,Year,Date,Amount,ExpenditureType
8,City of Chula Vista,SBCS CORPORATION,rental assistance,2017.0,10/23/2017,"$14,142.74",Prevention
9,City of Chula Vista,SBCS CORPORATION,rental assistance,2017.0,10/23/2017,"$12,931.10",Prevention
10,City of Chula Vista,SBCS CORPORATION,rental assistance,2017.0,10/23/2017,"$10,285.61",Prevention
11,City of Chula Vista,SBCS CORPORATION,homeless services,2017.0,11/7/2017,$276.00,Crisis Management
12,City of Chula Vista,INTERFAITH SHELTER NETWORK,shelter,2017.0,11/8/2017,"$1,971.50",Crisis Management
...,...,...,...,...,...,...,...
2026,City of Chula Vista,ONE TIME VENDOR,motel voucher,2021.0,12/23/2021,$560.30,Crisis Management
2027,City of Chula Vista,KIKU GARDENS,rental assistance,2021.0,12/28/2021,$212.00,Prevention
2028,City of Chula Vista,KIKU GARDENS,rental assistance,2021.0,12/28/2021,$212.00,Prevention
2029,City of Chula Vista,KIKU GARDENS,rental assistance,2021.0,12/28/2021,$212.00,Prevention
2030,City of Chula Vista,"MARK II, LP",rental assistance,2021.0,12/28/2021,"$1,668.00",Prevention

In [19]:
# Rename the columns
exp = exp.rename(columns={
    'Grantor': 'city', 
    'Grantee': 'grantee', 
    'Program': 'program', 
    'Year': 'year', 
    'Date': 'date', 
    'Amount': 'amount', 
    'ExpenditureType': 'exp_type'
})

# Try converting the 'date' column to datetime, allowing for mixed formats and coercing errors
exp['date'] = pd.to_datetime(exp['date'], format='mixed', errors='coerce')

# Check if any rows have invalid dates (i.e., rows where 'date' is NaT after coercion)
invalid_dates = exp[exp['date'].isna()]

# Add the "month" column with month names in word form
exp['month'] = exp['date'].dt.strftime('%B')

In [20]:
exp['program'].unique()

array(['rental assistance', 'homeless services', 'shelter',
       'motel voucher', 'rapid re housing', 'project h.o.p.e.',
       'take back the streets', 'work for hope',
       'housing navigation services', 'railing/fencing improvements',
       'facility improvement', 'housing assistance', 'outreach',
       'family reunification program',
       'general funding for homelessness services',
       'housing stability services', '211 assistance', 'case management',
       'flexible funds', 'point in time count',
       'consulting services homeless', 'communities in action',
       'legal services solutions for change',
       'translation homeless plan mtg', 'cdbg consolidated plan consult',
       'plha plan 7699835', 'homelessness prevention',
       'bridge to housing program', 'homeshare program',
       'homelessness educational initiatives',
       'training/technical assistance', 'restrooms', 'service center',
       'neighborhood revitalization services', 'employment/benefits', nan,
       'temporary housing and services', 'food and nutrition',
       'emergency stabalization and supportive services', 'call center',
       'safe parking', 'transitional storage', 'opening doors program',
       'bridge to housing network',
       'transitional housing and supportive services',
       'contract sobering services', 'interim housing facility'],
      dtype=object)

In [21]:
cleanexp = pd.read_csv('../data/processed/updated_dataset.csv')
cleanexp

,Unique.ID,Grantor,Grantee,Program,Year,Date,EndDate,Amount,AmendmentNumber,Funding.Agency,...,Issued,Funding.Type,Years,Average.By.Year,City.Year,Population,Amount.Per.Capita,Amount.Per.PEH,Population.PEH,ExpenditureType
0,NaN,City of Imperial Beach,NaN,NaN,2022.0,NaN,NaN,0,NaN,NaN,...,NaN,NaN,NaN,NaN,City of Imperial Beach|2022,NaN,$0.00,$0.00,0.0,Other/Unknown
1,NaN,City of Imperial Beach,NaN,NaN,2021.0,NaN,NaN,0,NaN,NaN,...,NaN,NaN,NaN,NaN,City of Imperial Beach|2021,NaN,$0.00,$0.00,0.0,Other/Unknown
2,NaN,City of Imperial Beach,NaN,NaN,2020.0,NaN,NaN,0,NaN,NaN,...,NaN,NaN,NaN,NaN,City of Imperial Beach|2020,NaN,$0.00,$0.00,16.0,Other/Unknown
3,NaN,City of Imperial Beach,NaN,NaN,2019.0,NaN,NaN,0,NaN,NaN,...,NaN,NaN,NaN,NaN,City of Imperial Beach|2019,NaN,$0.00,$0.00,12.0,Other/Unknown
4,NaN,City of Imperial Beach,NaN,NaN,2018.0,NaN,NaN,0,NaN,NaN,...,NaN,NaN,NaN,NaN,City of Imperial Beach|2018,NaN,$0.00,$0.00,7.0,Other/Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026,1066,City of Chula Vista,ONE TIME VENDOR,motel voucher,2021.0,12/23/2021,NaN,$560.30,NaN,CDBG,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Crisis Management
2027,NaN,City of Chula Vista,KIKU GARDENS,rental assistance,2021.0,12/28/2021,NaN,$212.00,NaN,HOME,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Prevention
2028,NaN,City of Chula Vista,KIKU GARDENS,rental assistance,2021.0,12/28/2021,NaN,$212.00,NaN,HOME,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Prevention
2029,NaN,City of Chula Vista,KIKU GARDENS,rental assistance,2021.0,12/28/2021,NaN,$212.00,NaN,HOME,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Prevention
2030,NaN,City of Chula Vista,"MARK II, LP",rental assistance,2021.0,12/28/2021,NaN,"$1,668.00",NaN,Housing Authority,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Prevention

In [22]:
cleanexp['Program'].unique()

array([nan, 'rental assistance', 'homeless services', 'shelter',
       'motel voucher', 'rapid re housing', 'project h.o.p.e.',
       'take back the streets', 'work for hope',
       'housing navigation services', 'railing/fencing improvements',
       'facility improvement', 'housing assistance', 'outreach',
       'family reunification program',
       'general funding for homelessness services',
       'housing stability services', '211 assistance', 'case management',
       'flexible funds', 'point in time count',
       'consulting services homeless', 'communities in action',
       'legal services solutions for change',
       'translation homeless plan mtg', 'cdbg consolidated plan consult',
       'plha plan 7699835', 'homelessness prevention',
       'bridge to housing program', 'homeshare program',
       'homelessness educational initiatives',
       'training/technical assistance', 'restrooms', 'service center',
       'neighborhood revitalization services', 'employment/benefits',
       'temporary housing and services', 'food and nutrition',
       'emergency stabalization and supportive services', 'call center',
       'safe parking', 'transitional storage', 'opening doors program',
       'bridge to housing network',
       'transitional housing and supportive services',
       'contract sobering services', 'interim housing facility'],
      dtype=object)

In [23]:
prog_to_drop = ['point in time count','railing/fencing improvements','facility improvement','training/technical assistance']
cleanexp = cleanexp[~cleanexp['Program'].isin(prog_to_drop)]
cleanexp = cleanexp.dropna(subset=['Program'])
cleanexp

,Unique.ID,Grantor,Grantee,Program,Year,Date,EndDate,Amount,AmendmentNumber,Funding.Agency,...,Issued,Funding.Type,Years,Average.By.Year,City.Year,Population,Amount.Per.Capita,Amount.Per.PEH,Population.PEH,ExpenditureType
8,NaN,City of Chula Vista,SBCS CORPORATION,rental assistance,2017.0,10/23/2017,NaN,"$14,142.74",NaN,NaN,...,NaN,NaN,NaN,NaN,City of Chula Vista|2017,266427.0,$0.05,$38.54,367.0,Prevention
9,NaN,City of Chula Vista,SBCS CORPORATION,rental assistance,2017.0,10/23/2017,NaN,"$12,931.10",NaN,NaN,...,NaN,NaN,NaN,NaN,City of Chula Vista|2017,266427.0,$0.05,$35.23,367.0,Prevention
10,NaN,City of Chula Vista,SBCS CORPORATION,rental assistance,2017.0,10/23/2017,NaN,"$10,285.61",NaN,NaN,...,NaN,NaN,NaN,NaN,City of Chula Vista|2017,266427.0,$0.04,$28.03,367.0,Prevention
11,1068,City of Chula Vista,SBCS CORPORATION,homeless services,2017.0,11/7/2017,NaN,$276.00,NaN,NaN,...,NaN,NaN,NaN,NaN,City of Chula Vista|2017,266427.0,$0.00,$0.75,367.0,Crisis Management
12,1067,City of Chula Vista,INTERFAITH SHELTER NETWORK,shelter,2017.0,11/8/2017,NaN,"$1,971.50",NaN,NaN,...,NaN,NaN,NaN,NaN,City of Chula Vista|2017,266427.0,$0.01,$5.37,367.0,Crisis Management
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026,1066,City of Chula Vista,ONE TIME VENDOR,motel voucher,2021.0,12/23/2021,NaN,$560.30,NaN,CDBG,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Crisis Management
2027,NaN,City of Chula Vista,KIKU GARDENS,rental assistance,2021.0,12/28/2021,NaN,$212.00,NaN,HOME,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Prevention
2028,NaN,City of Chula Vista,KIKU GARDENS,rental assistance,2021.0,12/28/2021,NaN,$212.00,NaN,HOME,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Prevention
2029,NaN,City of Chula Vista,KIKU GARDENS,rental assistance,2021.0,12/28/2021,NaN,$212.00,NaN,HOME,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Prevention
2030,NaN,City of Chula Vista,"MARK II, LP",rental assistance,2021.0,12/28/2021,NaN,"$1,668.00",NaN,Housing Authority,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Prevention

In [24]:
cleanexp.columns

Index(['Unique.ID', 'Grantor', 'Grantee', 'Program', 'Year', 'Date', 'EndDate',
       'Amount', 'AmendmentNumber', 'Funding.Agency', 'Funding.Source',
       'Category', 'Location', 'Issued', 'Funding.Type', 'Years',
       'Average.By.Year', 'City.Year', 'Population', 'Amount.Per.Capita',
       'Amount.Per.PEH', 'Population.PEH', 'ExpenditureType'],
      dtype='object')

In [25]:
col_to_drop = ['Unique.ID', 'EndDate', 'AmendmentNumber', 'Funding.Agency', 'Funding.Source', 'Category','Location', 'Issued', 'Funding.Type', 'Years','Average.By.Year', 'City.Year', 'Population', 'Amount.Per.Capita','Amount.Per.PEH', 'Population.PEH']
cleanexp = cleanexp.drop(columns=col_to_drop)
cleanexp

,Grantor,Grantee,Program,Year,Date,Amount,ExpenditureType
8,City of Chula Vista,SBCS CORPORATION,rental assistance,2017.0,10/23/2017,"$14,142.74",Prevention
9,City of Chula Vista,SBCS CORPORATION,rental assistance,2017.0,10/23/2017,"$12,931.10",Prevention
10,City of Chula Vista,SBCS CORPORATION,rental assistance,2017.0,10/23/2017,"$10,285.61",Prevention
11,City of Chula Vista,SBCS CORPORATION,homeless services,2017.0,11/7/2017,$276.00,Crisis Management
12,City of Chula Vista,INTERFAITH SHELTER NETWORK,shelter,2017.0,11/8/2017,"$1,971.50",Crisis Management
...,...,...,...,...,...,...,...
2026,City of Chula Vista,ONE TIME VENDOR,motel voucher,2021.0,12/23/2021,$560.30,Crisis Management
2027,City of Chula Vista,KIKU GARDENS,rental assistance,2021.0,12/28/2021,$212.00,Prevention
2028,City of Chula Vista,KIKU GARDENS,rental assistance,2021.0,12/28/2021,$212.00,Prevention
2029,City of Chula Vista,KIKU GARDENS,rental assistance,2021.0,12/28/2021,$212.00,Prevention
2030,City of Chula Vista,"MARK II, LP",rental assistance,2021.0,12/28/2021,"$1,668.00",Prevention

In [26]:
cleanexp['Program'].unique()

array(['rental assistance', 'homeless services', 'shelter',
       'motel voucher', 'rapid re housing', 'project h.o.p.e.',
       'take back the streets', 'work for hope',
       'housing navigation services', 'housing assistance', 'outreach',
       'family reunification program',
       'general funding for homelessness services',
       'housing stability services', '211 assistance', 'case management',
       'flexible funds', 'consulting services homeless',
       'communities in action', 'legal services solutions for change',
       'translation homeless plan mtg', 'cdbg consolidated plan consult',
       'plha plan 7699835', 'homelessness prevention',
       'bridge to housing program', 'homeshare program',
       'homelessness educational initiatives', 'restrooms',
       'service center', 'neighborhood revitalization services',
       'employment/benefits', 'temporary housing and services',
       'food and nutrition',
       'emergency stabalization and supportive services', 'call center',
       'safe parking', 'transitional storage', 'opening doors program',
       'bridge to housing network',
       'transitional housing and supportive services',
       'contract sobering services', 'interim housing facility'],
      dtype=object)

In [27]:

consolidation_map = {
    'flexible funds': ['general funding for homelessness services', 'flexible funds'],
    'transitional housing': ['temporary housing and services', 'transitional storage', 'transitional housing and supportive services', 'interim housing facility'],
    'emergency shelter': ['shelter', 'emergency stabilization and supportive services'],
    'staff and operations': ['211 assistance', 'case management', 'translation homeless plan mtg', 'cdbg consolidated plan consult', 'call center', 'employment/benefits']
}

cleanexp['Program'] = cleanexp['Program'].replace('emergency stabalization and supportive services', 'emergency shelter')

def consolidate_program(program):
    for consolidated_name, keywords in consolidation_map.items():
        if any(keyword in program.lower() for keyword in keywords):
            return consolidated_name
    return program  # Return original if no match

cleanexp['Program'] = cleanexp['Program'].apply(consolidate_program)
cleanexp['Program'].unique()

array(['rental assistance', 'homeless services', 'emergency shelter',
       'motel voucher', 'rapid re housing', 'project h.o.p.e.',
       'take back the streets', 'work for hope',
       'housing navigation services', 'housing assistance', 'outreach',
       'family reunification program', 'flexible funds',
       'housing stability services', 'staff and operations',
       'consulting services homeless', 'communities in action',
       'legal services solutions for change', 'plha plan 7699835',
       'homelessness prevention', 'bridge to housing program',
       'homeshare program', 'homelessness educational initiatives',
       'restrooms', 'service center',
       'neighborhood revitalization services', 'transitional housing',
       'food and nutrition', 'safe parking', 'opening doors program',
       'bridge to housing network', 'contract sobering services'],
      dtype=object)

## Data Merging `Updated_dataset.csv` with `PITCount.csv`

In [28]:
PIT = pd.read_csv('../data/raw/PITCount.csv')
PIT

,City,Year,Total PEH,Unsheltered PEH,Population,"PEH Per 100,000","Unsheltered Per 100,000",Latitude,Longitude
0,Carlsbad,2015,88,21,112662,78.109744,18.639825,33.158092,-117.350594
1,Chula Vista,2015,498,321,264206,188.489285,121.496105,32.639954,-117.106705
2,El Cajon,2015,711,191,103230,688.753269,185.023733,32.794773,-116.962524
3,Encinitas,2015,123,80,62590,196.517016,127.815945,33.039139,-117.295425
4,Escondido,2015,430,112,150683,285.367294,74.328225,33.124722,-117.080833
...,...,...,...,...,...,...,...,...,...
135,Poway,2024,1,1,47377,2.110729,2.110729,32.969895,-117.038479
136,San Diego,2024,6783,3489,1375452,493.146980,253.662069,32.715736,-117.161087
137,San Marcos,2024,35,35,94808,36.916716,36.916716,33.138500,-117.168800
138,Santee,2024,73,73,58150,125.537403,125.537403,32.838383,-116.973915
139,Vista,2024,271,170,97142,278.973050,175.001544,33.193611,-117.241112

In [29]:
cleanexp = cleanexp.rename(columns={
    'Grantor': 'City',
    'Grantee': 'Grantee',
    'Program': 'Program',
    'Year': 'Year',
    'Date': 'Date',
    'Amount': 'Amount',
    'ExpenditureType': 'ExpenditureType'
})

In [30]:
cleanexp['City'] = cleanexp['City'].str.replace('City of ', '')
cleanexp

,City,Grantee,Program,Year,Date,Amount,ExpenditureType
8,Chula Vista,SBCS CORPORATION,rental assistance,2017.0,10/23/2017,"$14,142.74",Prevention
9,Chula Vista,SBCS CORPORATION,rental assistance,2017.0,10/23/2017,"$12,931.10",Prevention
10,Chula Vista,SBCS CORPORATION,rental assistance,2017.0,10/23/2017,"$10,285.61",Prevention
11,Chula Vista,SBCS CORPORATION,homeless services,2017.0,11/7/2017,$276.00,Crisis Management
12,Chula Vista,INTERFAITH SHELTER NETWORK,emergency shelter,2017.0,11/8/2017,"$1,971.50",Crisis Management
...,...,...,...,...,...,...,...
2026,Chula Vista,ONE TIME VENDOR,motel voucher,2021.0,12/23/2021,$560.30,Crisis Management
2027,Chula Vista,KIKU GARDENS,rental assistance,2021.0,12/28/2021,$212.00,Prevention
2028,Chula Vista,KIKU GARDENS,rental assistance,2021.0,12/28/2021,$212.00,Prevention
2029,Chula Vista,KIKU GARDENS,rental assistance,2021.0,12/28/2021,$212.00,Prevention
2030,Chula Vista,"MARK II, LP",rental assistance,2021.0,12/28/2021,"$1,668.00",Prevention

In [31]:
cleanexp = cleanexp[~cleanexp['Year'].isna()]
cleanexp['Year'] = cleanexp['Year'].astype(int)
cleanexp

C:\Users\brand\AppData\Local\Temp\ipykernel_66148\708859221.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleanexp['Year'] = cleanexp['Year'].astype(int)

,City,Grantee,Program,Year,Date,Amount,ExpenditureType
8,Chula Vista,SBCS CORPORATION,rental assistance,2017,10/23/2017,"$14,142.74",Prevention
9,Chula Vista,SBCS CORPORATION,rental assistance,2017,10/23/2017,"$12,931.10",Prevention
10,Chula Vista,SBCS CORPORATION,rental assistance,2017,10/23/2017,"$10,285.61",Prevention
11,Chula Vista,SBCS CORPORATION,homeless services,2017,11/7/2017,$276.00,Crisis Management
12,Chula Vista,INTERFAITH SHELTER NETWORK,emergency shelter,2017,11/8/2017,"$1,971.50",Crisis Management
...,...,...,...,...,...,...,...
2026,Chula Vista,ONE TIME VENDOR,motel voucher,2021,12/23/2021,$560.30,Crisis Management
2027,Chula Vista,KIKU GARDENS,rental assistance,2021,12/28/2021,$212.00,Prevention
2028,Chula Vista,KIKU GARDENS,rental assistance,2021,12/28/2021,$212.00,Prevention
2029,Chula Vista,KIKU GARDENS,rental assistance,2021,12/28/2021,$212.00,Prevention
2030,Chula Vista,"MARK II, LP",rental assistance,2021,12/28/2021,"$1,668.00",Prevention

In [32]:
cleanexp['City'] = cleanexp['City'].replace('SDHC', 'San Diego')
PIT['Year'] -= 1 # Offset `Year` in `PIT` to have PIT assosiate with next "Observation" of PIT count of PEH
df = pd.merge(PIT, cleanexp, on=['City', 'Year'], how='inner')
df

C:\Users\brand\AppData\Local\Temp\ipykernel_66148\4119994460.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleanexp['City'] = cleanexp['City'].replace('SDHC', 'San Diego')

,City,Year,Total PEH,Unsheltered PEH,Population,"PEH Per 100,000","Unsheltered Per 100,000",Latitude,Longitude,Grantee,Program,Date,Amount,ExpenditureType
0,El Cajon,2014,711,191,103230,688.753269,185.023733,32.794773,-116.962524,East County Transitional Living Center,emergency shelter,7/1/2013,"$75,000.00",Crisis Management
1,El Cajon,2014,711,191,103230,688.753269,185.023733,32.794773,-116.962524,East County Transitional Living Center,emergency shelter,7/1/2013,"$75,000.00",Crisis Management
2,El Cajon,2015,321,218,103527,310.064041,210.573087,32.794773,-116.962524,East County Transitional Living Center,emergency shelter,7/1/2014,"$120,000.00",Crisis Management
3,El Cajon,2015,321,218,103527,310.064041,210.573087,32.794773,-116.962524,East County Transitional Living Center,emergency shelter,7/1/2014,"$120,000.00",Crisis Management
4,San Marcos,2015,99,44,94932,104.285173,46.348966,33.138500,-117.168800,North County Lifeline,housing assistance,NaN,21600,Prevention
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,San Diego,2022,6500,3285,1378307,471.593049,238.335871,32.715736,-117.161087,Father Joes Village,emergency shelter,7/1/2022,"$572,900.00",Crisis Management
596,San Marcos,2022,2,2,94832,2.108993,2.108993,33.138500,-117.168800,Alliance for Regional Solutions,emergency shelter,NaN,125000,Crisis Management
597,San Marcos,2022,2,2,94832,2.108993,2.108993,33.138500,-117.168800,211 San Diego,staff and operations,NaN,56792,Crisis Management
598,San Marcos,2022,2,2,94832,2.108993,2.108993,33.138500,-117.168800,Solutions for Change,flexible funds,NaN,21347,Crisis Management
599,Coronado,2023,0,0,19268,0.000000,0.000000,32.631718,-117.136772,St. Vincent de Paul Village,transitional housing,5/1/2023,95680.33,Crisis Management

In [33]:
df = df.drop(columns= ['Latitude', 'Longitude', 'Date'])
df['Amount'] = df['Amount'].str.replace('$', '', regex=False)
df['Amount'] = df['Amount'].str.replace(',', '',regex=False)
df

,City,Year,Total PEH,Unsheltered PEH,Population,"PEH Per 100,000","Unsheltered Per 100,000",Grantee,Program,Amount,ExpenditureType
0,El Cajon,2014,711,191,103230,688.753269,185.023733,East County Transitional Living Center,emergency shelter,75000.00,Crisis Management
1,El Cajon,2014,711,191,103230,688.753269,185.023733,East County Transitional Living Center,emergency shelter,75000.00,Crisis Management
2,El Cajon,2015,321,218,103527,310.064041,210.573087,East County Transitional Living Center,emergency shelter,120000.00,Crisis Management
3,El Cajon,2015,321,218,103527,310.064041,210.573087,East County Transitional Living Center,emergency shelter,120000.00,Crisis Management
4,San Marcos,2015,99,44,94932,104.285173,46.348966,North County Lifeline,housing assistance,21600,Prevention
...,...,...,...,...,...,...,...,...,...,...,...
595,San Diego,2022,6500,3285,1378307,471.593049,238.335871,Father Joes Village,emergency shelter,572900.00,Crisis Management
596,San Marcos,2022,2,2,94832,2.108993,2.108993,Alliance for Regional Solutions,emergency shelter,125000,Crisis Management
597,San Marcos,2022,2,2,94832,2.108993,2.108993,211 San Diego,staff and operations,56792,Crisis Management
598,San Marcos,2022,2,2,94832,2.108993,2.108993,Solutions for Change,flexible funds,21347,Crisis Management
599,Coronado,2023,0,0,19268,0.000000,0.000000,St. Vincent de Paul Village,transitional housing,95680.33,Crisis Management

In [ ]:
df['Year'] = df['Year'].replace(0, np.nan)
df = df.dropna()


df.to_csv('../data/processed/expenditures_and_PIT.csv', index=False)

## Data Merging `pivoted_dataset.csv` with `PITCount.csv`

In [36]:
pivoted = pd.read_csv('../data/processed/pivoted_dataset.csv')
pivoted.head()

,City,Year,bridge to housing network,emergency shelter,family reunification program,flexible funds,food and nutrition,homeless services,homelessness prevention,homeshare program,...,project h.o.p.e.,rapid re housing,rental assistance,restrooms,safe parking,service center,staff and operations,take back the streets,transitional housing,work for hope
0,Carlsbad,2017,0.0,14896.0,0.0,0.0,0.0,0.00,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Carlsbad,2018,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,122472.0,0.0,0.0,0.0
2,Carlsbad,2019,0.0,0.0,0.0,0.0,0.0,20000.00,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,122472.0,0.0,0.0,0.0
3,Carlsbad,2021,0.0,52574.0,0.0,0.0,0.0,419583.25,0.0,0.0,...,0.0,350000.0,41211.0,125000.0,0.0,204217.0,40000.0,0.0,0.0,0.0
4,Carlsbad,2022,0.0,202698.0,0.0,0.0,0.0,29825.00,0.0,0.0,...,0.0,350000.0,42396.0,25000.0,0.0,204217.0,180000.0,0.0,0.0,0.0

In [37]:
PIT.head()

,City,Year,Total PEH,Unsheltered PEH,Population,"PEH Per 100,000","Unsheltered Per 100,000",Latitude,Longitude
0,Carlsbad,2014,88,21,112662,78.109744,18.639825,33.158092,-117.350594
1,Chula Vista,2014,498,321,264206,188.489285,121.496105,32.639954,-117.106705
2,El Cajon,2014,711,191,103230,688.753269,185.023733,32.794773,-116.962524
3,Encinitas,2014,123,80,62590,196.517016,127.815945,33.039139,-117.295425
4,Escondido,2014,430,112,150683,285.367294,74.328225,33.124722,-117.080833

In [41]:
#PIT['Year'] -= 1 # Year already offset `Year` in `PIT` to have PIT assosiate with next "Observation" of PIT count of PEH
df = pd.merge(pivoted, PIT, on=['Year', 'City'], how='left')
df = df.drop(columns= ['Latitude', 'Longitude'])
df

,City,Year,bridge to housing network,emergency shelter,family reunification program,flexible funds,food and nutrition,homeless services,homelessness prevention,homeshare program,...,service center,staff and operations,take back the streets,transitional housing,work for hope,Total PEH,Unsheltered PEH,Population,"PEH Per 100,000","Unsheltered Per 100,000"
0,Carlsbad,2017,0.0,14896.00,0.0,0.0,0.000,0.00,0.0,0.0,...,0.0,0.00,0.0,0.00,0.00,210,152,115518,181.789851,131.581225
1,Carlsbad,2018,0.0,0.00,0.0,0.0,0.000,0.00,0.0,0.0,...,0.0,122472.00,0.0,0.00,0.00,161,102,115382,139.536496,88.402004
2,Carlsbad,2019,0.0,0.00,0.0,0.0,0.000,20000.00,0.0,0.0,...,0.0,122472.00,0.0,0.00,0.00,148,94,114747,128.979407,81.919353
3,Carlsbad,2021,0.0,52574.00,0.0,0.0,0.000,419583.25,0.0,0.0,...,204217.0,40000.00,0.0,0.00,0.00,118,75,114160,103.363700,65.697267
4,Carlsbad,2022,0.0,202698.00,0.0,0.0,0.000,29825.00,0.0,0.0,...,204217.0,180000.00,0.0,0.00,0.00,103,60,113792,90.516029,52.727784
5,Chula Vista,2017,0.0,3943.00,0.0,0.0,0.000,552.00,0.0,0.0,...,0.0,0.00,0.0,0.00,0.00,337,229,270819,124.437355,84.558321
6,Chula Vista,2018,0.0,18057.00,0.0,0.0,0.000,78548.00,0.0,0.0,...,0.0,0.00,0.0,0.00,0.00,321,242,274492,116.943299,88.162861
7,Chula Vista,2019,0.0,22000.00,0.0,0.0,0.000,91398.00,0.0,0.0,...,0.0,0.00,0.0,0.00,0.00,313,212,276041,113.388953,76.800185
8,Chula Vista,2021,0.0,30000.00,0.0,0.0,0.000,111454.00,0.0,0.0,...,0.0,0.00,200000.0,0.00,53671.56,309,206,279170,110.685245,73.790164
9,Coronado,2021,0.0,0.00,0.0,0.0,0.000,0.00,0.0,0.0,...,0.0,0.00,0.0,95680.33,0.00,1,1,18702,5.347022,5.347022
10,Coronado,2022,0.0,0.00,0.0,0.0,0.000,0.00,0.0,0.0,...,0.0,0.00,0.0,95680.33,0.00,1,1,18985,5.267316,5.267316
11,Coronado,2023,0.0,0.00,0.0,0.0,0.000,0.00,0.0,0.0,...,0.0,0.00,0.0,95680.33,0.00,0,0,19268,0.000000,0.000000
12,El Cajon,2014,0.0,150000.00,0.0,0.0,0.000,0.00,0.0,0.0,...,0.0,0.00,0.0,0.00,0.00,711,191,103230,688.753269,185.023733
13,El Cajon,2015,0.0,240000.00,0.0,0.0,0.000,0.00,0.0,0.0,...,0.0,0.00,0.0,0.00,0.00,321,218,103527,310.064041,210.573087
14,El Cajon,2016,0.0,216456.00,0.0,0.0,0.000,0.00,0.0,0.0,...,0.0,0.00,0.0,0.00,0.00,453,323,103486,437.740371,312.119514
15,El Cajon,2017,0.0,220000.00,0.0,0.0,0.000,0.00,0.0,0.0,...,0.0,0.00,0.0,0.00,0.00,679,288,103041,658.960996,279.500393
16,El Cajon,2018,0.0,20000.00,0.0,0.0,0.000,0.00,0.0,0.0,...,0.0,0.00,0.0,0.00,0.00,787,298,102708,766.249951,290.142929
17,El Cajon,2019,0.0,1549337.70,10000.0,0.0,0.000,0.00,0.0,0.0,...,0.0,0.00,0.0,0.00,0.00,784,310,106126,738.744511,292.105610
18,El Cajon,2021,0.0,221786.00,40000.0,0.0,0.000,0.00,0.0,0.0,...,0.0,0.00,0.0,0.00,0.00,1308,185,104414,1252.705576,177.179305
19,El Cajon,2022,0.0,0.00,0.0,0.0,0.000,0.00,0.0,0.0,...,0.0,0.00,0.0,0.00,0.00,1360,203,103558,1313.273721,196.025416
20,Encinitas,2018,6707.0,6707.00,0.0,0.0,0.000,0.00,13407.0,0.0,...,0.0,0.00,0.0,0.00,0.00,120,79,62709,191.360092,125.978727
21,Encinitas,2019,20054.0,0.00,0.0,0.0,0.000,0.00,13607.0,0.0,...,0.0,0.00,0.0,0.00,0.00,80,47,61988,129.057237,75.821127
22,Encinitas,2021,50256.0,0.00,0.0,0.0,83034.000,0.00,0.0,0.0,...,0.0,162500.00,0.0,0.00,0.00,113,76,61369,184.132054,123.841027
23,Encinitas,2022,0.0,0.00,0.0,0.0,0.000,0.00,0.0,0.0,...,0.0,162500.00,0.0,0.00,0.00,92,73,61085,150.609806,119.505607
24,Escondido,2017,0.0,43000.00,0.0,0.0,0.000,0.00,192324.0,0.0,...,0.0,0.00,0.0,0.00,0.00,411,263,151793,270.763474,173.262272
25,Escondido,2018,0.0,45000.00,0.0,0.0,0.000,0.00,0.0,0.0,...,0.0,0.00,0.0,0.00,0.00,350,241,151625,230.832646,158.944765
26,Escondido,2019,0.0,45000.00,0.0,0.0,0.000,0.00,0.0,0.0,...,0.0,185328.00,0.0,0.00,0.00,429,264,151038,284.034481,174.790450
27,Escondido,2021,0.0,0.00,0.0,0.0,0.000,0.00,0.0,0.0,...,0.0,0.00,0.0,0.00,0.00,499,182,150270,332.068943,121.115326
28,La Mesa,2021,0.0,0.00,0.0,377618.0,0.000,0.00,0.0,0.0,...,0.0,0.00,0.0,0.00,0.00,53,35,60360,87.806494,57.985421
29,La Mesa,2022,0.0,0.00,0.0,0.0,0.000,0.00,0.0,0.0,...,0.0,0.00,0.0,0.00,0.00,36,36,60005,59.995000,59.995000
30,Lemon Grove,2021,0.0,0.00,0.0,0.0,0.000,0.00,0.0,0.0,...,0.0,0.00,0.0,0.00,0.00,31,31,27224,113.870115,113.870115
31,National City,2017,0.0,0.00,0.0,0.0,0.000,0.00,0.0,0.0,...,0.0,0.00,0.0,0.00,0.00,233,201,61272,380.271576,328.045437
32,National City,2018,0.0,0.00,0.0,0.0,0.000,0.00,0.0,0.0,...,0.0,0.00,0.0,0.00,0.00,94,94,61394,153.109424,153.109424
33,National City,2021,0.0,0.00,0.0,0.0,0.000,0.00,0.0,0.0,...,0.0,313532.00,0.0,0.00,0.00,158,149,55550,284.428443,268.226823
34,Poway,2018,0.0,0.00,0.0,0.0,0.000,0.00,0.0,0.0,...,0.0,0.00,0.0,0.00,0.00,9,9,49323,18.247065,18.247065
35,Poway,2019,0.0,20000.00,0.0,0.0,0.000,0.00,0.0,0.0,...,0.0,0.00,0.0,0.00,0.00,15,15,48779,30.750938,30.750938
36,Poway,2021,0.0,0.00,0.0,0.0,168822.545,0.00,0.0,0.0,...,0.0,0.00,0.0,0.00,0.00,23,23,48078,47.838928,47.838928
37,San Diego,2017,0.0,6117446.00,394000.0,0.0,0.000,0.00,0.0,0.0,...,0.0,0.00,0.0,717118.00,0.00,4912,2630,1421917,345.449137,184.961569
38,San Diego,2018,0.0,0.00,844000.0,0.0,0.000,0.00,0.0,0.0,...,0.0,0.00,0.0,3656326.52,0.00,5082,2600,1423851,356.919369,182.603376
39,San Diego,2019,0.0,15693598.76,844000.0,0.0,0.000,0.00,0.0,0.0,...,0.0,0.00,0.0,4801341.54,0.00,4870,2283,1386872,352.375706,164.615047
40,San Diego,2021,0.0,20048336.80,894000.0,0.0,0.000,0.00,0.0,0.0,...,983751.0,74400.00,0.0,1341464.00,0.00,4801,2494,1381162,347.605857,180.572590
41,San Diego,2022,0.0,7144448.00,0.0,0.0,0.000,0.00,0.0,0.0,...,733751.0,76048.00,0.0,2191144.00,0.00,6500,3285,1378307,471.593049,238.335871
42,San Marcos,2015,0.0,0.00,0.0,0.0,0.000,0.00,0.0,0.0,...,0.0,17408.00,0.0,0.00,0.00,99,44,94932,104.285173,46.348966
43,San Marcos,2016,0.0,0.00,0.0,0.0,0.000,0.00,0.0,0.0,...,0.0,23210.67,0.0,0.00,0.00,170,52,95614,177.798230,54.385341
44,San Marcos,2017,0.0,62900.00,0.0,0.0,0.000,0.00,0.0,0.0,...,0.0,23210.67,0.0,0.00,0.00,62,62,96480,64.262023,64.262023
45,San Marcos,2018,0.0,66300.00,0.0,0.0,0.000,0.00,0.0,0.0,...,0.0,24275.67,0.0,0.00,0.00,46,46,96664,47.587520,47.587520
46,San Marcos,2019,0.0,125000.00,0.0,0.0,0.000,0.00,0.0,0.0,...,0.0,18473.00,0.0,0.00,0.00,8,8,94833,8.435882,8.435882
47,San Marcos,2021,0.0,125000.00,0.0,0.0,0.000,0.00,0.0,0.0,...,0.0,54763.00,0.0,0.00,0.00,12,12,94854,12.651022,12.651022
48,San Marcos,2022,0.0,125000.00,0.0,21347.0,0.000,0.00,0.0,0.0,...,0.0,56792.00,0.0,0.00,0.00,2,2,94832,2.108993,2.108993
49,Santee,2017,0.0,0.00,0.0,0.0,14470.000,0.00,5000.0,0.0,...,0.0,0.00,0.0,0.00,0.00,46,46,57944,79.386994,79.386994
50,Santee,2018,0.0,0.00,0.0,0.0,14270.000,0.00,5490.0,0.0,...,0.0,0.00,0.0,0.00,0.00,35,35,58081,60.260670,60.260670
51,Santee,2019,0.0,0.00,0.0,0.0,14050.000,0.00,5620.0,0.0,...,0.0,0.00,0.0,0.00,0.00,25,25,60037,41.640988,41.640988
52,Santee,2021,0.0,0.00,0.0,5000.0,0.000,6660.00,0.0,0.0,...,0.0,0.00,0.0,0.00,0.00,147,48,59051,248.937359,81.285668
53,Vista,2018,0.0,24740.00,0.0,0.0,0.000,0.00,0.0,0.0,...,0.0,0.00,0.0,0.00,0.00,296,122,101638,291.229658,120.033846
54,Vista,2019,0.0,26000.00,0.0,0.0,0.000,0.00,0.0,0.0,...,0.0,0.00,0.0,0.00,0.00,100,51,98381,101.645643,51.839278
55,Vista,2021,0.0,251267.00,0.0,0.0,0.000,0.00,0.0,35000.0,...,0.0,195700.00,0.0,0.00,0.00,117,76,97766,119.673506,77.736636

In [42]:
df.to_csv('../data/processed/pivoted_and_PIT.csv', index=False)